call intellisurround#register('<', '>')
call intellisurround#register('(', ')')
call intellisurround#register('{', '}')
call intellisurround#register('[', ']')
call intellisurround#register('`', '`')
call intellisurround#register("'", "'")
call intellisurround#register('"', '"')
